### ISSUE TITLE
Text Mangled/getting overwritten/missing in release 0.1.45

### ISSUE THREAD

**Issue by rampr** [gameclosure/native-ios#15]
Sometimes the text is mangled or duplicated like below, or goes missing after the game runs for a while. It only happens with buttonviews

Example of text getting duplicated(It should have been Resume & Map)
![photo](https://cloud.githubusercontent.com/assets/100719/2587338/41a78044-ba1c-11e3-9bff-7cc6482b1ad8.PNG)

Corresponding logs
2014-01-16 12:02:36.209 com.hashcube.sudokuquest[2302:60b] {canvas} WARNING: Failed to make complete framebuffer 36055
13:29
rampr: 2014-01-16 12:02:36.214 com.hashcube.sudokuquest[2302:60b] LOG .imageLoading {canvas-registry} Registering canvas: __canvas__2
13:29
rampr: 2014-01-16 12:02:36.215 com.hashcube.sudokuquest[2302:60b] {gl} Created context '43'
13:29
rampr: 2014-01-16 12:02:36.219 com.hashcube.sudokuquest[2302:60b] {tex} Unloaded 1 stale textures. Now: Texture count = 46. Bytes used = 48313344 -> 44119040 / 44282766
13:29
rampr: 2014-01-16 12:02:36.220 com.hashcube.sudokuquest[2302:60b] {core} WARNING: OpenGL error 1286

**Comment by jwilm** [comment]
@rampr is this still happening? We've made changes to the texture manager and font rendering since this was posted.

**Comment by rampr** [comment]
It used to happen with version 0.1.46 devkit1.

We'll soon migrate to devkit2 and I'll let you know.

**Comment by martell** [comment]
Closing old issues as this project is being deprecated.
If the new tealeaf project has this issue please reopen it here when it becomes available.
https://github.com/gameclosure/tealeaf
