### ISSUE TITLE
Ajax doesn't return when server is down/doesn't respond

### ISSUE THREAD

**Issue by rampr** [gameclosure/native-ios#16]
If the remove server is offline, ajax calls don't respond with an error. The calls never return

Seems to be happening with the latest version of devkit. Tested it on iOS only.

**Comment by jwilm** [comment]
Are you using `util.ajax`?

**Comment by rampr** [comment]
yeah I'm using util.ajax. This used to happen on release 0.1.46 of devkit1.

I'm not sure if it happens on devkit2.

**Comment by jwilm** [comment]
What do you mean by "remote server is offline"? Like the server is unreachable, or server is reachable but no service on port 80?  A little clarification would be helpful so I can dig into it.

Thanks!

**Comment by rampr** [comment]
Both ( when it is unreachable or not running on port 80）should have the same effect, the request would timeout.






On Wednesday, Feb 4, 2015 at 04:03, Joe Wilm <notifications@github.com>, wrote:

What do you mean by "remote server is offline"? Like the server is unreachable, or server is reachable but no service on port 80?  A little clarification would be helpful so I can dig into it.


Thanks!

**Comment by rampr** [comment]
I recently tested on a non existent server, it fails on ios but works on android

**Comment by martell** [comment]
Closing old issues as this project is being deprecated.
If the new tealeaf project has this issue please reopen it here when it becomes available.
https://github.com/gameclosure/tealeaf
