### ISSUE TITLE
TeaLeafIos Crash on IOS7 iPHONE 5S

### ISSUE THREAD

**Issue by etamity** [gameclosure/native-ios#17]
'loading.png'
2014-05-02 11:12:56.094 TeaLeafIOS[9238:60b] {core} Initialization complete
(lldb) 

libobjc.A.dylib`objc_msgSend:
0x3aaa1620:  cbz    r0, 0x3aaa165e            ; objc_msgSend + 62
0x3aaa1622:  ldr.w  r9, [r0]
0x3aaa1626:  ldrh.w r12, [r9, #12]                <-- Stop at here(Thread 1:EXC_BAD_ACCESS (code=1,address=0xa001800c))
0x3aaa162a:  ldr.w  r9, [r9, #8]
0x3aaa162e:  and.w  r12, r12, r1
0x3aaa1632:  add.w  r9, r9, r12, lsl #3

Anyone can Help??

**Comment by martell** [comment]
Closing old issues as this project is being deprecated.
If the new tealeaf project has this issue please reopen it here when it becomes available.
https://github.com/gameclosure/tealeaf
