### ISSUE TITLE
Initialize spidermonkey in separate thread

### ISSUE THREAD

**Issue by jwilm** [gameclosure/native-ios#38]
Before migrating to spidermonkey 28, the JS runtime startup was done in a separate thread. Since the threading requirements changed, the runtime startup is now done on the main thread. However, this is not strictly necessary. From [the mozilla blog](https://blog.mozilla.org/luke/2012/01/24/jsruntime-is-now-officially-single-threaded/),

> THE SINGLE-THREADED INVARIANT IN DETAIL

> Each runtime now has an “owner thread” (JSRuntime::ownerThread). The “owner thread” is the id of the only OS thread allowed to touch the runtime. This owner thread is set to the current thread (PR_GetCurrentThread()) from JS_NewRuntime and may only be changed — when no JS is executing in the runtime — via JS_ClearRuntimeThread/JS_SetRuntimeThread. Virtually every JSAPI function that takes a JSContext parameter will assert that PR_GetCurrentThread == cx->runtime->ownerThread().

**Comment by martell** [comment]
Hi @jwilm :)
I'm just going to close this as we are moving towards open sourcing the new tealeaf project you worked on. Will be using JavaScriptCore and not spidermonkey also (at least for ios for now).
