### ISSUE TITLE
Adding custom bundles to native-ios build?

### ISSUE THREAD

**Issue by kunal2619** [gameclosure/native-ios#44]
Is it possible to add custom bundle to resources for ios builds. I tried adding custom bundles the same way as resources.bundle is added. I tried other ways too like constructing the bundle again while building. But it did not work too. How should i go about solving this issue?

**Comment by martell** [comment]
Hi @kunal2619,
You should be able to manually add resources to the project after running
```
devkit debug native-ios
```
The folder you are looking for is deep in build/debug/native-ios
If you want to hack on it a little to add resources for every new project you can probably add resource to 
modules/native-ios/tree/master/tealeaf/resources/resources.bundle after running devkit install on your project
